version: '2.3'
networks:
  default:
    driver: bridge

services:
  mysql:
    container_name: teste-mysql
    image: mysql:8.3.0
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=teste-app
